Importing the libraries

In [1]:
import numpy as np
import pandas as pd

pulling the data

In [2]:
dataset = pd.read_csv("njmin3.csv")

checking the data

In [3]:
dataset.describe()
pd.set_option("display.max_columns", None)
dataset

,NJ,POST_APRIL92,NJ_POST_APRIL92,fte,bk,kfc,roys,wendys,co_owned,centralj,southj,pa1,pa2,demp
0,1,0,0,15.00,1,0,0,0,0,1,0,0,0,12.00
1,1,0,0,15.00,1,0,0,0,0,1,0,0,0,6.50
2,1,0,0,24.00,0,0,1,0,0,1,0,0,0,-1.00
3,1,0,0,19.25,0,0,1,0,1,0,0,0,0,2.25
4,1,0,0,21.50,1,0,0,0,0,0,0,0,0,13.00
5,1,0,0,9.50,0,1,0,0,0,0,0,0,0,1.00
6,1,0,0,44.00,0,0,0,1,0,0,0,0,0,-27.50
7,1,0,0,NaN,1,0,0,0,0,0,0,0,0,NaN
8,1,0,0,21.00,1,0,0,0,0,0,0,0,0,17.00
9,1,0,0,28.00,0,0,0,1,0,0,1,0,0,8.00
10,1,0,0,10.00,0,0,0,1,0,0,1,0,0,6.00
11,1,0,0,20.50,1,0,0,0,0,0,0,0,0,0.00
12,1,0,0,25.50,0,0,1,0,1,0,0,0,0,-6.50
13,1,0,0,19.00,0,0,0,1,0,0,0,0,0,34.00
14,1,0,0,16.50,1,0,0,0,0,0,1,0,0,0.00
15,1,0,0,17.00,1,0,0,0,1,0,1,0,0,-0.50
16,1,0,0,27.50,1,0,0,0,1,0,0,0,0,17.50
17,1,0,0,5.00,0,0,1,0,1,1,0,0,0,3.00
18,1,0,0,16.00,0,1,0,0,0,1,0,0,0,-0.50
19,1,0,0,41.50,1,0,0,0,0,0,0,0,0,-17.50
20,1,0,0,13.00,0,1,0,0,1,1,0,0,0,-5.50
21,1,0,0,10.00,0,1,0,0,0,0,0,0,0,-2.50
22,1,0,0,15.00,0,1,0,0,0,1,0,0,0,3.50
23,1,0,0,26.00,0,0,1,0,0,0,0,0,0,-9.50
24,1,0,0,18.00,0,0,0,1,0,1,0,0,0,15.50
25,1,0,0,35.00,0,0,1,0,0,0,0,0,0,2.00
26,1,0,0,21.00,0,0,1,0,1,0,0,0,0,-3.00
27,1,0,0,34.50,0,0,0,1,0,0,0,0,0,-8.00
28,1,0,0,18.25,0,0,0,1,0,0,0,0,0,14.75
29,1,0,0,24.50,0,0,0,1,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
790,0,1,0,18.00,0,0,0,1,0,0,0,1,0,-20.00
791,0,1,0,19.00,0,0,0,1,0,0,0,1,0,1.50
792,0,1,0,31.50,0,0,0,1,0,0,0,1,0,6.50
793,0,1,0,23.00,1,0,0,0,0,0,0,0,1,NaN
794,0,1,0,24.50,1,0,0,0,0,0,0,0,1,3.50
795,0,1,0,27.50,1,0,0,0,0,0,0,0,1,12.00
796,0,1,0,34.50,1,0,0,0,0,0,0,0,1,19.00
797,0,1,0,14.00,0,1,0,0,1,0,0,0,1,5.50
798,0,1,0,15.00,0,0,1,0,1,0,0,0,1,-3.00
799,0,1,0,23.00,0,0,0,1,0,0,0,0,1,2.25
800,0,1,0,26.50,1,0,0,0,0,0,0,0,1,-12.50
801,0,1,0,23.50,1,0,0,0,0,0,0,0,1,-18.00
802,0,1,0,35.50,1,0,0,0,0,0,0,0,1,13.00
803,0,1,0,21.00,1,0,0,0,0,0,0,0,1,-11.00
804,0,1,0,23.00,1,0,0,0,0,0,0,1,0,-1.00
805,0,1,0,20.00,1,0,0,0,0,0,0,0,1,-6.00
806,0,1,0,27.00,1,0,0,0,0,0,0,1,0,-21.50
807,0,1,0,13.00,0,1,0,0,1,0,0,0,1,4.50
808,0,1,0,0.00,0,0,1,0,0,0,0,0,1,-18.50
809,0,1,0,13.50,0,0,1,0,1,0,0,0,1,0.50
810,0,1,0,NaN,0,0,0,1,1,0,0,0,1,NaN
811,0,1,0,26.75,0,0,0,1,1,0,0,0,1,-1.25
812,0,1,0,43.50,1,0,0,0,0,0,0,0,1,19.00
813,0,1,0,41.25,1,0,0,0,0,0,0,0,1,22.75
814,0,1,0,14.25,0,0,1,0,1,0,0,0,1,-9.25
815,0,1,0,12.50,0,0,1,0,1,0,0,0,1,-2.50
816,0,1,0,34.00,0,0,1,0,0,0,0,0,1,16.00
817,0,1,0,10.00,0,0,1,0,1,0,0,0,1,-10.25
818,0,1,0,14.00,1,0,0,0,0,0,0,1,0,-1.50
819,0,1,0,17.50,1,0,0,0,0,0,0,1,0,-3.50

check if there are more NAs

In [4]:
dataset.isnull().any()

NJ                 False
POST_APRIL92       False
NJ_POST_APRIL92    False
fte                 True
bk                 False
kfc                False
roys               False
wendys             False
co_owned           False
centralj           False
southj             False
pa1                False
pa2                False
demp                True
dtype: bool

replacing NAs with averages

In [5]:
from sklearn.impute import SimpleImputer
missingvalues = SimpleImputer(missing_values = np.nan,
                              strategy = "mean")
missingvalues = missingvalues.fit(dataset[['fte', 'demp']])
dataset[['fte', 'demp']] = missingvalues.transform(dataset[['fte', 'demp']])

check if there are more NAs

In [24]:
dataset.isnull().any()

NJ                 False
POST_APRIL92       False
NJ_POST_APRIL92    False
fte                False
bk                 False
kfc                False
roys               False
wendys             False
co_owned           False
centralj           False
southj             False
pa1                False
pa2                False
demp               False
dtype: bool

In [7]:
dataset

,NJ,POST_APRIL92,NJ_POST_APRIL92,fte,bk,kfc,roys,wendys,co_owned,centralj,southj,pa1,pa2,demp
0,1,0,0,15.000000,1,0,0,0,0,1,0,0,0,12.000000
1,1,0,0,15.000000,1,0,0,0,0,1,0,0,0,6.500000
2,1,0,0,24.000000,0,0,1,0,0,1,0,0,0,-1.000000
3,1,0,0,19.250000,0,0,1,0,1,0,0,0,0,2.250000
4,1,0,0,21.500000,1,0,0,0,0,0,0,0,0,13.000000
5,1,0,0,9.500000,0,1,0,0,0,0,0,0,0,1.000000
6,1,0,0,44.000000,0,0,0,1,0,0,0,0,0,-27.500000
7,1,0,0,21.026511,1,0,0,0,0,0,0,0,0,-0.070443
8,1,0,0,21.000000,1,0,0,0,0,0,0,0,0,17.000000
9,1,0,0,28.000000,0,0,0,1,0,0,1,0,0,8.000000
10,1,0,0,10.000000,0,0,0,1,0,0,1,0,0,6.000000
11,1,0,0,20.500000,1,0,0,0,0,0,0,0,0,0.000000
12,1,0,0,25.500000,0,0,1,0,1,0,0,0,0,-6.500000
13,1,0,0,19.000000,0,0,0,1,0,0,0,0,0,34.000000
14,1,0,0,16.500000,1,0,0,0,0,0,1,0,0,0.000000
15,1,0,0,17.000000,1,0,0,0,1,0,1,0,0,-0.500000
16,1,0,0,27.500000,1,0,0,0,1,0,0,0,0,17.500000
17,1,0,0,5.000000,0,0,1,0,1,1,0,0,0,3.000000
18,1,0,0,16.000000,0,1,0,0,0,1,0,0,0,-0.500000
19,1,0,0,41.500000,1,0,0,0,0,0,0,0,0,-17.500000
20,1,0,0,13.000000,0,1,0,0,1,1,0,0,0,-5.500000
21,1,0,0,10.000000,0,1,0,0,0,0,0,0,0,-2.500000
22,1,0,0,15.000000,0,1,0,0,0,1,0,0,0,3.500000
23,1,0,0,26.000000,0,0,1,0,0,0,0,0,0,-9.500000
24,1,0,0,18.000000,0,0,0,1,0,1,0,0,0,15.500000
25,1,0,0,35.000000,0,0,1,0,0,0,0,0,0,2.000000
26,1,0,0,21.000000,0,0,1,0,1,0,0,0,0,-3.000000
27,1,0,0,34.500000,0,0,0,1,0,0,0,0,0,-8.000000
28,1,0,0,18.250000,0,0,0,1,0,0,0,0,0,14.750000
29,1,0,0,24.500000,0,0,0,1,0,0,0,0,0,-0.070443
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
790,0,1,0,18.000000,0,0,0,1,0,0,0,1,0,-20.000000
791,0,1,0,19.000000,0,0,0,1,0,0,0,1,0,1.500000
792,0,1,0,31.500000,0,0,0,1,0,0,0,1,0,6.500000
793,0,1,0,23.000000,1,0,0,0,0,0,0,0,1,-0.070443
794,0,1,0,24.500000,1,0,0,0,0,0,0,0,1,3.500000
795,0,1,0,27.500000,1,0,0,0,0,0,0,0,1,12.000000
796,0,1,0,34.500000,1,0,0,0,0,0,0,0,1,19.000000
797,0,1,0,14.000000,0,1,0,0,1,0,0,0,1,5.500000
798,0,1,0,15.000000,0,0,1,0,1,0,0,0,1,-3.000000
799,0,1,0,23.000000,0,0,0,1,0,0,0,0,1,2.250000
800,0,1,0,26.500000,1,0,0,0,0,0,0,0,1,-12.500000
801,0,1,0,23.500000,1,0,0,0,0,0,0,0,1,-18.000000
802,0,1,0,35.500000,1,0,0,0,0,0,0,0,1,13.000000
803,0,1,0,21.000000,1,0,0,0,0,0,0,0,1,-11.000000
804,0,1,0,23.000000,1,0,0,0,0,0,0,1,0,-1.000000
805,0,1,0,20.000000,1,0,0,0,0,0,0,0,1,-6.000000
806,0,1,0,27.000000,1,0,0,0,0,0,0,1,0,-21.500000
807,0,1,0,13.000000,0,1,0,0,1,0,0,0,1,4.500000
808,0,1,0,0.000000,0,0,1,0,0,0,0,0,1,-18.500000
809,0,1,0,13.500000,0,0,1,0,1,0,0,0,1,0.500000
810,0,1,0,21.026511,0,0,0,1,1,0,0,0,1,-0.070443
811,0,1,0,26.750000,0,0,0,1,1,0,0,0,1,-1.250000
812,0,1,0,43.500000,1,0,0,0,0,0,0,0,1,19.000000
813,0,1,0,41.250000,1,0,0,0,0,0,0,0,1,22.750000
814,0,1,0,14.250000,0,0,1,0,1,0,0,0,1,-9.250000
815,0,1,0,12.500000,0,0,1,0,1,0,0,0,1,-2.500000
816,0,1,0,34.000000,0,0,1,0,0,0,0,0,1,16.000000
817,0,1,0,10.000000,0,0,1,0,1,0,0,0,1,-10.250000
818,0,1,0,14.000000,1,0,0,0,0,0,0,1,0,-1.500000
819,0,1,0,17.500000,1,0,0,0,0,0,0,1,0,-3.500000

isolating the X and Y variables

In [8]:
X = dataset.iloc[:,0:3].values

In [9]:
X

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       ...,
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0]], dtype=int64)

In [10]:
Y = dataset.iloc[:,3].values

In [11]:
Y

array([15.        , 15.        , 24.        , 19.25      , 21.5       ,
        9.5       , 44.        , 21.02651134, 21.        , 28.        ,
       10.        , 20.5       , 25.5       , 19.        , 16.5       ,
       17.        , 27.5       ,  5.        , 16.        , 41.5       ,
       13.        , 10.        , 15.        , 26.        , 18.        ,
       35.        , 21.        , 34.5       , 18.25      , 24.5       ,
       20.        , 16.        , 17.5       , 20.5       , 20.        ,
       12.25      , 33.        , 31.5       , 21.02651134, 18.        ,
       28.        , 16.5       , 14.75      , 23.5       , 10.        ,
       46.5       , 15.5       , 24.5       , 24.        , 23.        ,
       28.        , 32.5       , 23.        , 17.        , 30.        ,
       21.5       , 32.        ,  8.        , 35.5       , 31.5       ,
       33.        , 22.        , 23.        , 23.        ,  8.5       ,
       12.5       ,  9.5       , 13.        , 17.        ,  9.        ,
       19.        , 11.5       , 13.        , 48.        , 45.5       ,
       15.        , 18.        , 21.        , 20.5       , 20.5       ,
       17.5       , 27.5       , 24.        , 34.        , 18.        ,
       24.        , 21.02651134, 33.5       , 12.        , 35.        ,
       35.        , 16.        , 15.5       , 19.        , 24.        ,
       21.02651134, 36.        , 29.        , 29.        , 21.25      ,
       15.5       , 19.5       , 21.        , 14.        , 30.5       ,
       23.5       , 14.        , 14.5       , 15.5       , 26.5       ,
        8.        ,  5.5       , 23.25      , 15.5       , 32.25      ,
       30.        , 21.02651134, 30.5       , 14.        , 27.        ,
       18.5       , 38.        , 16.5       , 50.        , 20.5       ,
        6.5       , 13.5       , 28.        , 21.5       , 21.02651134,
       24.        , 20.5       , 21.02651134, 23.5       , 23.        ,
       17.        , 20.5       , 23.5       ,  9.5       , 10.        ,
       14.        , 85.        , 15.        , 21.5       , 53.        ,
       24.        , 20.5       , 14.5       , 25.        , 27.        ,
       22.5       , 36.5       , 17.25      , 21.5       , 24.5       ,
       19.        , 25.        , 16.        , 19.        , 22.75      ,
       35.        , 16.        , 21.        , 26.75      , 30.5       ,
       23.        , 21.5       , 36.5       , 23.        , 14.        ,
       17.25      , 18.5       ,  8.5       , 14.        , 23.        ,
       29.        , 19.        , 21.        , 17.        , 36.        ,
       25.        , 29.5       , 22.        , 11.        , 13.5       ,
       13.5       , 18.        ,  9.5       , 24.        , 14.5       ,
       29.        , 10.5       , 18.        , 21.02651134,  9.        ,
       33.        , 19.5       , 41.        , 17.        , 18.25      ,
       17.        , 32.        , 26.        , 11.5       , 21.        ,
       22.75      , 18.5       , 20.        , 18.        , 10.5       ,
       10.5       , 11.        , 10.5       , 12.5       , 18.        ,
       17.        , 15.        , 19.5       , 13.        , 20.25      ,
       26.        , 15.5       , 24.        , 25.5       , 14.5       ,
       21.5       , 14.        , 20.        , 22.5       , 30.        ,
       24.        , 22.        , 13.        ,  5.        , 13.5       ,
       28.        , 18.        , 24.        , 16.5       ,  7.        ,
       11.        , 19.5       , 10.        , 13.        , 10.        ,
       12.5       ,  8.        , 12.        , 20.5       , 18.5       ,
       11.5       , 15.        , 13.        , 10.        , 17.        ,
       17.        , 20.5       , 15.5       , 19.5       , 30.5       ,
       23.        , 13.        , 30.25      , 18.        , 10.        ,
       19.5       , 17.        , 25.5       ,  6.        , 11.5       ,
        8.5       , 18.5       , 15.5       , 14.25      , 38.        ,
       24.75      , 23.        , 24.        ,  7.5       , 15.        ,
        9.25      , 11.25      , 16.5       , 18.75      , 13.5       ,
       21.75      , 13.5       , 15.        , 17.5       , 17.5       ,
       21.02651134, 15.5       , 16.5       , 13.5       , 13.        ,
       11.5       , 29.05      , 13.        , 18.        , 30.        ,
       20.5       , 10.        , 21.02651134, 26.        , 12.5       ,
       19.5       , 12.        , 36.        , 21.        , 24.5       ,
       20.        , 26.5       , 15.        , 19.        , 17.5       ,
       20.5       , 21.        , 10.5       , 23.        , 23.        ,
       29.        , 21.        , 41.5       , 12.        , 33.        ,
        6.5       ,  9.        ,  9.75      , 24.5       , 14.        ,
       19.5       , 27.        , 21.5       , 23.        , 21.5       ,
       34.5       , 10.5       , 16.5       , 23.        , 38.        ,
       36.        , 16.        , 20.5       , 19.        , 53.        ,
       16.5       , 16.5       , 45.        ,  8.        , 15.5       ,
       24.        ,  7.5       ,  7.5       , 18.5       , 16.5       ,
       33.5       , 37.        , 18.        , 26.5       , 33.        ,
       21.02651134, 20.5       , 24.5       , 16.        , 21.02651134,
       23.5       , 13.        , 20.        , 22.        , 28.5       ,
       21.02651134, 25.5       , 18.        ,  9.        , 26.5       ,
        0.        , 23.75      , 18.        , 36.        , 21.        ,
       15.5       , 22.5       , 27.        , 34.        , 16.75      ,
       26.        , 18.        , 20.5       , 15.        , 25.5       ,
       21.02651134, 20.        , 18.        , 26.5       , 23.25      ,
       10.5       , 12.        ,  9.5       , 15.5       , 14.5       ,
       14.        ,  6.5       , 10.        , 11.5       , 46.5       ,
       26.5       , 16.        , 13.        , 14.        , 15.5       ,
       18.        , 27.        , 27.        , 29.5       , 16.5       ,
       31.5       , 27.5       , 25.5       , 32.        , 14.5       ,
       10.5       , 44.        , 15.5       , 10.5       , 24.        ,
       29.        , 30.5       , 20.        , 26.5       , 27.        ,
       26.5       , 10.5       , 18.        , 18.5       , 25.5       ,
       32.        , 33.        ,  7.5       , 12.5       , 24.        ,
       29.        , 10.        ,  9.5       , 17.5       , 17.5       ,
       25.        , 26.        , 24.        , 22.5       , 21.02651134,
       35.        , 17.75      , 24.5       , 16.5       , 30.        ,
       39.        , 17.        , 12.5       , 38.5       , 20.        ,
       21.        , 32.        , 19.        , 20.        , 26.5       ,
       19.        , 20.        , 22.5       , 10.        , 12.5       ,
       11.        , 12.5       , 59.        , 19.        , 15.5       ,
       19.        , 26.5       , 17.5       , 20.5       , 28.        ,
       30.25      , 44.        , 17.5       , 31.        , 31.        ,
       28.5       , 19.        , 41.        , 28.        ,  9.5       ,
       25.        , 28.        , 16.        , 22.75      , 21.02651134,
       32.        , 27.5       , 25.5       , 60.5       , 20.5       ,
       16.        , 25.        , 13.        ,  9.        , 16.5       ,
       21.        , 21.5       , 20.        , 21.25      , 21.5       ,
       31.        , 33.        , 37.75      ,  9.        , 11.        ,
       12.75      , 10.5       , 22.        ,  8.        , 25.        ,
       12.5       , 22.5       , 11.5       , 23.5       , 30.        ,
       16.5       , 29.        , 30.        , 22.5       , 24.        ,
       21.75      , 13.5       , 24.        , 28.5       , 10.        ,
       23.5       , 30.5       , 24.75      , 22.5       , 28.        ,
       14.        ,  9.        ,  9.5       , 15.5       , 12.        ,
       11.5       , 12.5       , 16.        , 28.5       , 15.        ,
       23.5       , 30.5       , 26.5       , 27.        , 21.5       ,
       21.02651134, 21.5       , 37.5       , 11.5       , 21.        ,
       28.        , 24.        , 23.        , 19.        ,  7.        ,
       14.        , 21.02651134, 32.        , 22.        , 14.25      ,
       16.5       ,  0.        , 47.5       , 15.5       , 10.5       ,
        7.        , 11.        ,  8.5       ,  0.        , 15.        ,
       13.5       , 12.5       , 12.5       , 12.5       , 10.        ,
       13.5       , 16.        , 23.5       , 21.02651134, 34.        ,
       32.5       , 21.5       , 20.        , 43.5       , 17.5       ,
        7.        , 21.02651134, 22.        , 22.        ,  7.        ,
       14.        , 27.        , 18.5       , 11.5       , 16.        ,
       25.        , 30.5       , 11.5       , 25.5       ,  9.5       ,
       11.5       , 12.        ,  0.        , 17.        , 24.        ,
       21.02651134, 21.02651134, 13.5       , 17.        , 28.        ,
       21.5       , 30.        , 19.5       , 20.        , 14.5       ,
       14.5       ,  0.        , 31.5       , 11.5       , 20.        ,
       34.        , 25.        , 10.        , 18.        , 25.        ,
       23.        , 17.5       , 23.        , 26.        , 16.5       ,
       35.5       , 31.        , 23.        , 22.5       , 21.5       ,
       12.        , 20.5       , 25.        ,  8.5       , 13.        ,
       21.5       , 23.        , 25.5       , 21.5       ,  9.5       ,
       36.5       , 16.        , 23.75      , 17.5       , 20.5       ,
       20.5       , 25.        , 40.5       , 13.75      ,  8.5       ,
       34.        , 24.        , 20.5       , 70.5       , 23.5       ,
       11.        ,  9.        , 15.5       , 58.        , 26.5       ,
       28.5       , 13.5       , 16.75      ,  9.5       , 15.        ,
       29.5       , 18.5       , 20.25      , 36.        , 21.        ,
       20.5       , 19.        , 14.        , 19.        , 32.5       ,
       19.        , 27.        , 19.5       , 24.        , 18.        ,
       21.02651134, 19.        , 14.        , 10.5       , 38.        ,
       23.5       , 10.5       , 25.        , 11.        , 36.5       ,
       52.5       , 29.        , 45.        , 22.75      ,  7.5       ,
       15.5       , 38.        , 17.5       , 25.        , 21.02651134,
       21.        , 15.5       , 15.5       ,  8.5       , 18.        ,
       20.75      , 39.        , 41.5       , 22.5       , 32.        ,
       24.        , 26.        , 48.5       ,  8.5       , 18.5       ,
       13.        , 22.5       , 28.        , 24.5       , 18.5       ,
       23.5       , 15.        , 18.        , 20.25      , 15.5       ,
       21.        , 24.        , 11.5       , 10.5       , 20.        ,
       35.5       , 21.02651134, 29.        , 36.5       , 11.        ,
        8.5       , 17.5       , 29.        , 30.5       , 26.        ,
       18.        , 20.        , 13.5       , 19.        , 15.5       ,
       14.5       , 14.        , 19.        , 21.        , 18.        ,
       20.5       , 13.5       , 17.5       , 25.5       , 15.5       ,
       25.5       , 27.        , 16.        , 19.        , 24.5       ,
       25.        , 17.        , 16.5       , 20.        , 18.        ,
       12.        , 25.        , 11.        , 27.        , 34.        ,
       25.        , 37.5       , 21.        ,  9.5       , 18.        ,
       18.        , 19.        , 31.5       , 23.        , 24.5       ,
       27.5       , 34.5       , 14.        , 15.        , 23.        ,
       26.5       , 23.5       , 35.5       , 21.        , 23.        ,
       20.        , 27.        , 13.        ,  0.        , 13.5       ,
       21.02651134, 26.75      , 43.5       , 41.25      , 14.25      ,
       12.5       , 34.        , 10.        , 14.        , 17.5       ])

creating the first model

In [12]:
import statsmodels.api as sm
X = sm.add_constant(X)
model1 = sm.OLS(Y, X).fit()

In [13]:
model1.summary(yname = "fte", 
               xname = ("intercept", "New Jersey", "After April 1992", "New Jersey and after April 1992"))

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    fte   R-squared:                       0.007
Model:                            OLS   Adj. R-squared:                  0.004
Method:                 Least Squares   F-statistic:                     1.974
Date:                Fri, 08 Oct 2021   Prob (F-statistic):              0.116
Time:                        17:57:34   Log-Likelihood:                -2986.2
No. Observations:                 820   AIC:                             5980.
Df Residuals:                     816   BIC:                             5999.
Df Model:                           3
Covariance Type:            nonrobust
===================================================================================================
                                      coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
intercept                          23.2728      1.041     22.349      0.000      21.229      25.317
New Jersey                         -2.8157      1.159     -2.430      0.015      -5.091      -0.541
After April 1992                   -2.1108      1.473     -1.433      0.152      -5.001       0.780
New Jersey and after April 1992     2.6810      1.639      1.636      0.102      -0.536       5.898
==============================================================================
Omnibus:                      232.659   Durbin-Watson:                   1.847
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              908.337
Skew:                           1.289   Prob(JB):                    5.72e-198
Kurtosis:                       7.465   Cond. No.                         11.4
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

Isolating the X and Y variables part 2

In [18]:
X = dataset.loc[:,['NJ', "POST_APRIL92", "NJ_POST_APRIL92", "bk", "kfc", "wendys"]].values

creating the second model

In [19]:
X = sm.add_constant(X)
model2 = sm.OLS(Y, X).fit()
model2.summary(yname = "fte", 
               xname = ("intercept", "New Jersey", "After April 1992", "New Jersey and after April 1992", "Burger King", "KFC", "Wendy's"))

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    fte   R-squared:                       0.191
Model:                            OLS   Adj. R-squared:                  0.185
Method:                 Least Squares   F-statistic:                     31.95
Date:                Fri, 08 Oct 2021   Prob (F-statistic):           1.30e-34
Time:                        18:09:45   Log-Likelihood:                -2902.4
No. Observations:                 820   AIC:                             5819.
Df Residuals:                     813   BIC:                             5852.
Df Model:                           6
Covariance Type:            nonrobust
===================================================================================================
                                      coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
intercept                          23.4055      1.085     21.575      0.000      21.276      25.535
New Jersey                         -2.2349      1.050     -2.129      0.034      -4.296      -0.174
After April 1992                   -2.1108      1.332     -1.585      0.113      -4.725       0.504
New Jersey and after April 1992     2.6810      1.482      1.809      0.071      -0.229       5.591
Burger King                         2.1620      0.748      2.891      0.004       0.694       3.630
KFC                                -8.4912      0.890     -9.540      0.000     -10.238      -6.744
Wendy's                             1.0496      0.970      1.082      0.280      -0.855       2.954
==============================================================================
Omnibus:                      300.626   Durbin-Watson:                   1.965
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1848.909
Skew:                           1.530   Prob(JB):                         0.00
Kurtosis:                       9.690   Cond. No.                         12.0
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

Isolating the X and Y variables part 3

In [27]:
X = dataset.loc[:,['NJ', "POST_APRIL92", "NJ_POST_APRIL92", "bk", "kfc", "wendys", "co_owned", "centralj", "southj" ]].values

creating the third model

In [28]:
X = sm.add_constant(X)
model3 = sm.OLS(Y, X).fit()
model3.summary(yname = "fte", 
               xname = ("intercept", "New Jersey", "After April 1992", "New Jersey and after April 1992", "Burger King", "KFC", "Wendy's", "co_owned", "Central J", "South J"))

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    fte   R-squared:                       0.217
Model:                            OLS   Adj. R-squared:                  0.208
Method:                 Least Squares   F-statistic:                     24.89
Date:                Fri, 08 Oct 2021   Prob (F-statistic):           6.45e-38
Time:                        18:27:59   Log-Likelihood:                -2889.1
No. Observations:                 820   AIC:                             5798.
Df Residuals:                     810   BIC:                             5845.
Df Model:                           9
Covariance Type:            nonrobust
===================================================================================================
                                      coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
intercept                          23.9321      1.184     20.204      0.000      21.607      26.257
New Jersey                         -1.3009      1.078     -1.207      0.228      -3.416       0.815
After April 1992                   -2.1108      1.313     -1.608      0.108      -4.688       0.466
New Jersey and after April 1992     2.6810      1.461      1.835      0.067      -0.187       5.549
Burger King                         1.6653      0.832      2.002      0.046       0.033       3.298
KFC                                -8.2346      0.899     -9.161      0.000      -9.999      -6.470
Wendy's                             0.6218      1.017      0.612      0.541      -1.374       2.617
co_owned                           -0.7456      0.699     -1.066      0.287      -2.118       0.627
Central J                           0.0030      0.867      0.003      0.997      -1.699       1.705
South J                            -3.5487      0.759     -4.674      0.000      -5.039      -2.058
==============================================================================
Omnibus:                      309.762   Durbin-Watson:                   2.047
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1987.511
Skew:                           1.570   Prob(JB):                         0.00
Kurtosis:                       9.951   Cond. No.                         12.6
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""